let protoColors = `#000000	black	black	noir	黑
#006400	darkgreen	green	vert	绿
#008000	green	green	vert	绿
#00FF00	lime	green	vert	绿
#7CFC00	lawngreen	green	vert	绿
#7FFF00	chartreuse	green	vert	绿
#800000	maroon	brown	brun	棕
#808000	olive	green	vert	绿
#8B0000	darkred	red	rouge	红
#FF0000	red	red	rouge	红
#FF4500	orangered	red	rouge	红
#FF8C00	darkorange	orange	orange	橙
#FFA500	orange	orange	orange	橙
#FFD700	gold	yellow	jaune	黄
#FFFF00	yellow	yellow	jaune	黄
#B8860B	darkgoldenrod	yellow	jaune	黄
#8B4513	saddlebrown	brown	brun	棕
#D2691E	chocolate	orange	orange	橙
#DAA520	goldenrod	orange	orange	橙
#228B22	forestgreen	green	vert	绿
#B22222	firebrick	red	rouge	红
#6B8E23	olivedrab	green	vert	绿
#A52A2A	brown	red	rouge	红
#A0522D	sienna	brown	brun	棕
#556B2F	darkolivegreen	green	vert	绿
#ADFF2F	greenyellow	green	vert	绿
#32CD32	limegreen	green	vert	绿
#9ACD32	yellowgreen	green	vert	绿
#DC143C	crimson	red	rouge	红
#CD853F	peru	orange	orange	橙
#FF6347	tomato	orange	orange	橙
#2F4F4F	darkslategray	gray	gris	灰
#FF7F50	coral	orange	orange	橙
#2E8B57	seagreen	green	vert	绿
#CD5C5C	indianred	red	rouge	红
#F4A460	sandybrown	orange	orange	橙
#696969	dimgray	gray	gris	灰
#BDB76B	darkkhaki	green	vert	绿
#191970	midnightblue	indigo	indigo	靛青
#3CB371	mediumseagreen	green	vert	绿
#FA8072	salmon	salmon	saumon	鲑鱼
#E9967A	darksalmon	salmon	saumon	鲑鱼
#FFA07A	lightsalmon	salmon	saumon	鲑鱼
#00FF7F	springgreen	green	vert	绿
#7F7F7F	gray	gray	gris	灰
#000080	navy	indigo	indigo	靛青
#008080	teal	teal	bleu	蓝绿
#800080	purple	purple	violet	紫
#F08080	lightcoral	pink	rose	粉
#4B0082	indigo	purple	violet	紫
#C71585	mediumvioletred	magenta	magenta	品红
#DEB887	burlywood	beige	beige	浅褐
#00008B	darkblue	indigo	indigo	靛青
#008B8B	darkcyan	teal	bleu	蓝绿
#483D8B	darkslateblue	blue	bleu	蓝
#8B008B	darkmagenta	purple	violet	紫
#D2B48C	tan	beige	beige	浅褐
#F0E68C	khaki	yellow	jaune	黄
#8FBC8F	darkseagreen	green	vert	绿
#BC8F8F	rosybrown	beige	beige	浅褐
#708090	slategray	gray	gris	灰
#90EE90	lightgreen	green	vert	绿
#DB7093	palevioletred	pink	rose	粉
#FF1493	deeppink	magenta	magenta	品红
#98FB98	palegreen	green	vert	绿
#778899	lightslategray	gray	gris	灰
#00FA9A	mediumspringgreen	green	vert	绿
#5F9EA0	cadetblue	teal	bleu	蓝绿
#A9A9A9	darkgray	gray	gris	灰
#20B2AA	lightseagreen	teal	bleu	蓝绿
#66CDAA	mediumaquamarine	teal	bleu	蓝绿
#EEE8AA	palegoldenrod	yellow	jaune	黄
#FFDEAD	navajowhite	beige	beige	浅褐
#F5DEB3	wheat	beige	beige	浅褐
#4682B4	steelblue	blue	bleu	蓝
#FF69B4	hotpink	pink	rose	粉
#FFE4B5	moccasin	beige	beige	浅褐
#FFDAB9	peachpuff	beige	beige	浅褐
#C0C0C0	silver	gray	gris	灰
#FFB6C1	lightpink	pink	rose	粉
#FFE4C4	bisque	beige	beige	浅褐
#FFC0CB	pink	pink	rose	粉
#48D1CC	mediumturquoise	blue	bleu	蓝
#9932CC	darkorchid	purple	violet	紫
#0000CD	mediumblue	blue	bleu	蓝
#6A5ACD	slateblue	blue	bleu	蓝
#FFEBCD	blanchedalmond	beige	beige	浅褐
#FFFACD	lemonchiffon	beige	beige	浅褐
#40E0D0	turquoise	blue	bleu	蓝
#00CED1	darkturquoise	blue	bleu	蓝
#FAFAD2	lightgoldenrodyellow	beige	beige	浅褐
#9400D3	darkviolet	purple	violet	紫
#BA55D3	mediumorchid	purple	violet	紫
#D3D3D3	lightgrey	white	blanc	白
#7FFFD4	aquamarine	green	vert	绿
#FFEFD5	papayawhip	beige	beige	浅褐
#DA70D6	orchid	magenta	magenta	品红
#FAEBD7	antiquewhite	beige	beige	浅褐
#D8BFD8	thistle	purple	violet	紫
#9370DB	mediumpurple	purple	violet	紫
#DCDCDC	gainsboro	white	blanc	白
#F5F5DC	beige	beige	beige	浅褐
#FFF8DC	cornsilk	beige	beige	浅褐
#DDA0DD	plum	purple	violet	紫
#B0C4DE	lightsteelblue	purple	violet	紫
#9FAFDF	navyblue	purple	violet	紫
#FFFFE0	lightyellow	beige	beige	浅褐
#4169E1	royalblue	blue	bleu	蓝
#FFE4E1	mistyrose	pink	rose	粉
#8A2BE2	blueviolet	purple	violet	紫
#ADD8E6	lightblue	blue	bleu	蓝
#B0E0E6	powderblue	blue	bleu	蓝
#FAF0E6	linen	beige	beige	浅褐
#FDF5E6	oldlace	beige	beige	浅褐
#87CEEB	skyblue	blue	bleu	蓝
#6495ED	cornflowerblue	blue	bleu	蓝
#7B68EE	mediumslateblue	purple	violet	紫
#AFEEEE	paleturquoise	blue	bleu	蓝
#EE82EE	violet	pink	rose	粉
#FFF5EE	seashell	white	blanc	白
#F0FFF0	honeydew	white	blanc	白
#FFFAF0	floralwhite	white	blanc	白
#FFFFF0	ivory	white	blanc	白
#F5F5F5	whitesmoke	white	blanc	白
#FFF0F5	lavenderblush	white	blanc	白
#87CEFA	lightskyblue	blue	bleu	蓝
#E6E6FA	lavender	purple	violet	紫
#F5FFFA	mintcream	white	blanc	白
#FFFAFA	snow	white	blanc	白
#0000FF	blue	blue	bleu	蓝
#00BFFF	deepskyblue	blue	bleu	蓝
#00FFFF	aqua	blue	bleu	蓝
#00FFFF	cyan	blue	bleu	蓝
#1E90FF	dodgerblue	blue	bleu	蓝
#E0FFFF	lightcyan	white	blanc	白
#F0F8FF	aliceblue	white	blanc	白
#F0FFFF	azure	white	blanc	白
#F8F8FF	ghostwhite	white	blanc	白
#FF00FF	fuchsia	magenta	magenta	品
#FF00FF	magenta	magenta	magenta	品
#FFFFFF	white	white	blanc	白`.split("\n").map(function(line) {
	let [hex, label, en, fr, zh] = line.split("\t");
	let obj = {};
	obj["color:"+label] = {en, fr, zh}
	Talktalk.provide(obj);
	return {
		color: new Color(hex),
		label
	};
});