let bug = [];

bug.push({name:"Common Butterfly",found:"Flying",bells:160,annual:[t,t,t,t,t,t,f,f,t,t,t,t],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Yellow Butterfly",found:"Flying",bells:160,annual:[f,f,t,t,t,t,f,f,t,t,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Tiger Butterfly",found:"Flying",bells:240,annual:[f,f,t,t,t,t,t,t,t,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Peacock Butterfly",found:"Flying by hybrid flowers",bells:2500,annual:[f,f,t,t,t,t,f,f,f,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Common Bluebottle",found:"Flying",bells:300,annual:[f,f,f,t,t,t,t,t,f,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Paper Kite Butterfly",found:"Flying",bells:1000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Great Purple Emperor",found:"Flying",bells:3000,annual:[f,f,f,f,t,t,t,t,f,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Monach Butterfly",found:"Flying",bells:140,annual:[f,f,f,f,f,f,f,f,t,t,t,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Emperor Butterfly",found:"Flying",bells:4000,annual:[t,t,t,f,f,t,t,t,t,f,f,t],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Agrias Butterfly",found:"Flying",bells:3000,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Raja Brooke's Birdwing",found:"Flying by purple flowers",bells:2500,annual:[t,t,f,t,t,t,t,t,t,f,f,t],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Queen Alexandra's Birdwing",found:"Flying",bells:4000,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Moth",found:"Flying by light",bells:130,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Atlas Moth",found:"On trees",bells:3000,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Madagascan Sunset Moth",found:"Flying",bells:2500,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Long Locust",found:"On ground",bells:200,annual:[f,f,f,t,t,t,t,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Migratory Locust",found:"On ground",bells:600,annual:[f,f,f,f,f,f,f,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Rice Grasshopper",found:"On ground",bells:160,annual:[f,f,f,f,f,f,f,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Grasshopper",found:"On ground",bells:160,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Cricket",found:"Dig at cricket noise",bells:130,annual:[f,f,f,f,f,f,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Bell Cricket",found:"On ground",bells:430,annual:[f,f,f,f,f,f,f,f,t,t,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Mantis",found:"On flowers",bells:430,annual:[f,f,t,t,t,t,t,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Orchid Mantis",found:"On white flowers",bells:2400,annual:[f,f,t,t,t,t,t,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Honeybee",found:"Flying",bells:200,annual:[f,f,t,t,t,t,t,f,f,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Wasp",found:"Falls from shaking trees",bells:2500,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Brown Cicada",found:"On trees",bells:250,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Robust Cicada",found:"On trees",bells:300,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Giant Cicada",found:"On trees",bells:600,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Walker Cicada",found:"On trees",bells:400,annual:[f,f,f,f,f,f,f,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Evening Cicada",found:"On trees",bells:660,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Cicada Shell",found:"On trees",bells:10,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Red Dragonfly",found:"Flying",bells:180,annual:[f,f,f,f,f,f,f,f,t,t,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Darner Dragonfly",found:"Flying",bells:230,annual:[f,f,f,t,t,t,t,t,t,t,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Banded Dragonfly",found:"Flying",bells:4500,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Damselfly",found:"Flying",bells:500,annual:[t,t,f,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Firefly",found:"Flying",bells:300,annual:[f,f,f,f,f,t,f,f,f,f,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Mole Cricket",found:"Underground",bells:500,annual:[t,t,t,t,t,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Pondskater",found:"Ponds",bells:130,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Diving Beetle",found:"Ponds and rivers",bells:800,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],size:"bug"});
bug.push({name:"Giant Water Bug",found:"Ponds and rivers",bells:2000,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Stinkbug",found:"On flowers",bells:120,annual:[f,f,t,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Man-faced Stink Bug",found:"On flowers",bells:1000,annual:[f,f,t,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Ladybug",found:"On flowers",bells:200,annual:[f,f,t,t,f,f,f,f,f,t,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Tiger Beetle",found:"On ground",bells:1500,annual:[f,t,t,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Jewel Beetle",found:"On tree stumps",bells:2400,annual:[f,f,f,t,t,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Violin Beetle",found:"On tree stumps",bells:450,annual:[f,f,f,f,t,t,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Citrus Long-horned Beetle",found:"On tree stumps",bells:350,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Rosalia Batesi Beetle",found:"On tree stumps",bells:3000,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Blue Weevil Beetle",found:"On palm trees",bells:800,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Dung Beetle",found:"Pushing snowballs",bells:3000,annual:[t,t,f,f,f,f,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Earth-boring Dung Beetle",found:"On ground",bells:300,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t],size:"bug"});
bug.push({name:"Scarab Beetle",found:"On trees",bells:10000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Drone Beetle",found:"On trees",bells:200,annual:[f,f,f,f,f,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Goliath Beetle",found:"On coconut trees",bells:8000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Saw Stag",found:"On trees",bells:2000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Miyama Stag",found:"On trees",bells:1000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t],size:"bug"});
bug.push({name:"Giant Stag",found:"On trees",bells:10000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Rainbow Stag",found:"On trees",bells:6000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Cyclommatus Stag",found:"On trees",bells:8000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Golden Stag",found:"On trees",bells:12000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Giraffe Stag",found:"On trees",bells:12000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Horned Dynastid",found:"On trees",bells:1350,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Horned Atlas",found:"On trees",bells:8000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Horned Elephant",found:"On trees",bells:8000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Horned Herucles",found:"On trees",bells:12000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f],size:"bug"});
bug.push({name:"Walking Stick",found:"On trees",bells:600,annual:[f,f,f,f,f,f,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Walking Leaf",found:"Near trees, looks like leaf",bells:600,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Bagworm",found:"Falls from shaking trees",bells:600,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Ant",found:"On rotten food",bells:80,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Hermit Crab",found:"Beach",bells:1000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Wharf Roach",found:"On rocks at beach",bells:200,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Fly",found:"On trash items",bells:60,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Mosquito",found:"Flying",bells:130,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Flea",found:"On villagers",bells:70,annual:[f,f,f,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"bug"});
bug.push({name:"Snail",found:"On rocks with rain",bells:250,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t],size:"bug"});
bug.push({name:"Pill Bug",found:"Hit rocks",bells:250,annual:[t,t,t,t,t,t,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t],size:"bug"});
bug.push({name:"Centipede",found:"Hit rocks",bells:300,annual:[t,t,t,t,t,t,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Spider",found:"Falls from shaking trees",bells:480,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Tarantula",found:"On ground",bells:8000,annual:[t,t,t,t,f,f,f,f,f,f,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});
bug.push({name:"Scorpion",found:"On ground",bells:8000,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],size:"bug"});