let deep = [];

deep.push(["Seaweed","Stationary",600,[t,t,t,t,t,t,t,f,f,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
deep.push(["Sea grapes","Stationary",900,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Sea cucumber","Slow consistent movement",500,[t,t,t,t,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Sea pig","Quick long lunges",10000,[t,t,f,f,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Sea star","Slow short lunges",500,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Sea urchin","Slow consistent movement",1700,[f,f,f,f,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Slate pencil urchin","Moderate consistent movement",2000,[f,f,f,f,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Sea anemone","Stationary",500,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
deep.push(["Moon jellyfish","Slow consistent movement",600,[f,f,f,f,f,f,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Sea slug","Slow consistent movement",600,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
deep.push(["Pearl oyster","Moderate long lunges",2800,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Mussel","Slow consistent movement",1500,[f,f,f,f,f,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Oyster","Moderate short lunges",1100,[t,t,f,f,f,f,f,f,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Scallop","Slow long lunges",1200,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Whelk","Slow consistent movement",1000,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Turban shell","Slow",1000,[f,f,t,t,t,f,f,f,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Abalone","Moderate consistent movement",2000,[t,f,f,f,f,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Gigas giant clam","Quick long lunges",15000,[f,f,f,f,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Large"]);
deep.push(["Chambered nautilus","Slow",1800,[f,f,t,t,t,t,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Octopus","Moderate long lunges",1200,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Umbrella octopus","Quick long lunges",6000,[f,f,t,t,t,f,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Vampire squid","Quick long lunges",10000,[f,f,f,f,t,t,t,t,f,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Firefly squid","Slow",1400,[f,f,t,t,t,t,f,f,f,f,f,f],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"X Small"]);
deep.push(["Gazami crab","Moderate long lunges",2200,[f,f,f,f,f,t,t,t,t,t,t,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Dungeoness crab","Moderate consistent movement",1900,[t,t,t,t,t,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
deep.push(["Snow crab","Quick short lunges",6000,[t,t,t,t,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
deep.push(["Red king crab","Quick",8000,[t,t,t,f,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
deep.push(["Acorn barnacle","Stationary",600,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
deep.push(["Spider crab","Quick",12000,[f,f,t,t,f,f,f,f,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Large"]);
deep.push(["Tiger prawn","Moderate consistent movement",3000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Sweet shrimp","Slow",1400,[t,t,f,f,f,f,f,f,t,t,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Mantis shrimp","Quick short lunges",2500,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Spiny Lobster","Fast",5000,[f,f,f,f,f,f,f,f,f,t,t,t],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"Large"]);
deep.push(["Lobster","Quick",4500,[t,f,f,t,t,t,f,f,f,f,f,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
deep.push(["Giant isopod","Quick long lunges",12000,[f,f,f,f,f,f,t,t,t,t,f,f],[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],"Medium"]);
deep.push(["Horseshoe crab","Quick short lunges",2500,[f,f,f,f,f,f,t,t,t,f,f,f],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"Medium"]);
deep.push(["Sea pineapple","Slow long lunges",1500,[f,f,f,t,t,t,t,t,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
deep.push(["Spotted garden eel","Slow consistent movement",1100,[f,f,f,f,t,t,t,t,t,t,f,f],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,,,],"Small"]);
deep.push(["Flatworm","Slow short movement",700,[f,f,f,f,f,f,f,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"X Small"]);
deep.push(["Venus' flower basket","Quick long lunges",5000,[t,t,f,f,f,f,f,f,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);