let deep = [];

deep.push({name:"Seaweed",found:"Stationary",bells:600,annual:[t,t,t,t,t,t,t,f,f,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
deep.push({name:"Sea grapes",found:"Stationary",bells:900,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Sea cucumber",found:"Slow consistent movement",bells:500,annual:[t,t,t,t,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Sea pig",found:"Quick long lunges",bells:10000,annual:[t,t,f,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Sea star",found:"Slow short lunges",bells:500,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Sea urchin",found:"Slow consistent movement",bells:1700,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Slate pencil urchin",found:"Moderate consistent movement",bells:2000,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Sea anemone",found:"Stationary",bells:500,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
deep.push({name:"Moon jellyfish",found:"Slow consistent movement",bells:600,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Sea slug",found:"Slow consistent movement",bells:600,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
deep.push({name:"Pearl oyster",found:"Moderate long lunges",bells:2800,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Mussel",found:"Slow consistent movement",bells:1500,annual:[f,f,f,f,f,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Oyster",found:"Moderate short lunges",bells:1100,annual:[t,t,f,f,f,f,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Scallop",found:"Slow long lunges",bells:1200,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Whelk",found:"Slow consistent movement",bells:1000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Turban shell",found:"Slow",bells:1000,annual:[f,f,t,t,t,f,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Abalone",found:"Moderate consistent movement",bells:2000,annual:[t,f,f,f,f,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Gigas giant clam",found:"Quick long lunges",bells:15000,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Large"});
deep.push({name:"Chambered nautilus",found:"Slow",bells:1800,annual:[f,f,t,t,t,t,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Octopus",found:"Moderate long lunges",bells:1200,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Umbrella octopus",found:"Quick long lunges",bells:6000,annual:[f,f,t,t,t,f,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Vampire squid",found:"Quick long lunges",bells:10000,annual:[f,f,f,f,t,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Firefly squid",found:"Slow",bells:1400,annual:[f,f,t,t,t,t,f,f,f,f,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"X Small"});
deep.push({name:"Gazami crab",found:"Moderate long lunges",bells:2200,annual:[f,f,f,f,f,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Dungeoness crab",found:"Moderate consistent movement",bells:1900,annual:[t,t,t,t,t,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
deep.push({name:"Snow crab",found:"Quick short lunges",bells:6000,annual:[t,t,t,t,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
deep.push({name:"Red king crab",found:"Quick",bells:8000,annual:[t,t,t,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
deep.push({name:"Acorn barnacle",found:"Stationary",bells:600,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
deep.push({name:"Spider crab",found:"Quick",bells:12000,annual:[f,f,t,t,f,f,f,f,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Large"});
deep.push({name:"Tiger prawn",found:"Moderate consistent movement",bells:3000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Sweet shrimp",found:"Slow",bells:1400,annual:[t,t,f,f,f,f,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Mantis shrimp",found:"Quick short lunges",bells:2500,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Spiny Lobster",found:"Fast",bells:5000,annual:[f,f,f,f,f,f,f,f,f,t,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"Large"});
deep.push({name:"Lobster",found:"Quick",bells:4500,annual:[t,f,f,t,t,t,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
deep.push({name:"Giant isopod",found:"Quick long lunges",bells:12000,annual:[f,f,f,f,f,f,t,t,t,t,f,f],daily:[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],size:"Medium"});
deep.push({name:"Horseshoe crab",found:"Quick short lunges",bells:2500,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"Medium"});
deep.push({name:"Sea pineapple",found:"Slow long lunges",bells:1500,annual:[f,f,f,t,t,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
deep.push({name:"Spotted garden eel",found:"Slow consistent movement",bells:1100,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,,,],size:"Small"});
deep.push({name:"Flatworm",found:"Slow short movement",bells:700,annual:[f,f,f,f,f,f,f,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"X Small"});
deep.push({name:"Venus' flower basket",found:"Quick long lunges",bells:5000,annual:[t,t,f,f,f,f,f,f,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});