let fish = [];

fish.push({name:"Bitterling",found:"River",bells:900,annual:[t,t,t,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Pale Chub",found:"River",bells:160,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"X Small"});
fish.push({name:"Crucian Carp",found:"River",bells:160,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Dace",found:"River",bells:240,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Carp",found:"Pond",bells:300,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Koi",found:"Pond",bells:4000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Goldfish",found:"Pond",bells:1300,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Pop-eyed Goldfish",found:"Pond",bells:1300,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"X Small"});
fish.push({name:"Ranchu Goldfish",found:"Pond",bells:4500,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"Small"});
fish.push({name:"Killifish",found:"Pond",bells:300,annual:[f,f,f,t,t,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Crawfish",found:"Pond",bells:200,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Soft-shelled Turtle",found:"River",bells:3750,annual:[f,f,f,f,f,f,f,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Snapping Turtle",found:"River",bells:5000,annual:[f,f,f,t,t,t,t,t,t,t,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"X Large"});
fish.push({name:"Tadpole",found:"Pond",bells:100,annual:[f,f,t,t,t,t,t,f,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Frog",found:"Pond",bells:120,annual:[f,f,f,f,t,t,t,t,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Freshwater Goby",found:"River",bells:400,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Loach",found:"River",bells:400,annual:[f,f,t,t,t,f,f,f,f,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Catfish",found:"Pond",bells:800,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Giant Snakehead",found:"Pond",bells:5500,annual:[f,f,f,f,f,t,t,t,f,f,f,f],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"X Large"});
fish.push({name:"Bluegill",found:"River",bells:180,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"Small"});
fish.push({name:"Yellow Perch",found:"River",bells:300,annual:[t,t,t,f,f,f,f,f,f,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Black Bass",found:"River",bells:400,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Tilapia",found:"River",bells:800,annual:[f,f,f,f,f,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Pike",found:"River",bells:1800,annual:[f,f,f,f,f,f,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Large"});
fish.push({name:"Pond Smelt",found:"River",bells:500,annual:[t,t,f,f,f,f,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Sweetfish",found:"River",bells:900,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Cherry Salmon",found:"Clifftop river",bells:1000,annual:[f,f,t,t,t,t,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Char",found:"Clifftop river",bells:3800,annual:[f,f,t,t,t,t,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Golden Trout",found:"Clifftop river",bells:15000,annual:[f,f,t,t,t,t,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Stringfish",found:"Clifftop river",bells:15000,annual:[t,t,t,f,f,f,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Salmon",found:"Mouth of river",bells:700,annual:[f,f,f,f,f,f,f,f,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"King Salmon",found:"Mouth of river",bells:1800,annual:[f,f,f,f,f,f,f,f,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Mitten Crab",found:"River",bells:2000,annual:[f,f,f,f,f,f,f,f,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Guppy",found:"River",bells:1300,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"X Small"});
fish.push({name:"Nibble Fish",found:"River",bells:1500,annual:[f,f,f,f,t,t,t,t,t,f,f,f],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"Small"});
fish.push({name:"Angelfish",found:"River",bells:3000,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Betta",found:"River",bells:2500,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"Small"});
fish.push({name:"Neon Tetra",found:"River",bells:500,annual:[f,f,f,t,t,t,t,t,t,t,t,f],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"X Small"});
fish.push({name:"Rainbowfish",found:"River",bells:800,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],size:"Small"});
fish.push({name:"Piranha",found:"River",bells:2500,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],size:"Small"});
fish.push({name:"Arowana",found:"River",bells:10000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Dorado",found:"River",bells:15000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],size:"X Large"});
fish.push({name:"Gar",found:"Pond",bells:6000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Arapaima",found:"River",bells:10000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Saddled Bichir",found:"River",bells:4000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"Large"});
fish.push({name:"Sturgeon",found:"Mouth of river",bells:10000,annual:[t,t,t,f,f,f,f,f,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Sea Butterfly",found:"Sea",bells:1000,annual:[t,t,t,f,f,f,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Sea Horse",found:"Sea",bells:1100,annual:[f,f,f,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Clown Fish",found:"Sea",bells:650,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Small"});
fish.push({name:"Surgeonfish",found:"Sea",bells:1000,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Butterfly Fish",found:"Sea",bells:1000,annual:[f,f,f,t,t,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Napoleonfish",found:"Sea",bells:10000,annual:[f,f,f,f,f,f,t,t,f,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],size:"Giant"});
fish.push({name:"Zebra Turkeyfish",found:"Sea",bells:500,annual:[f,f,f,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Blowfish",found:"Sea",bells:5000,annual:[t,t,f,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Puffer Fish",found:"Sea",bells:250,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Anchovy",found:"Sea",bells:200,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],size:"Small"});
fish.push({name:"Horse Mackerel",found:"Sea",bells:150,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Small"});
fish.push({name:"Barred Knifejaw",found:"Sea",bells:5000,annual:[f,f,t,t,t,t,t,t,t,t,t,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Sea Bass",found:"Sea",bells:400,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"X Large"});
fish.push({name:"Red Snapper",found:"Sea",bells:3000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Dab",found:"Sea",bells:300,annual:[t,t,t,t,f,f,f,f,f,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Olive Flounder",found:"Sea",bells:800,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Squid",found:"Sea",bells:500,annual:[t,t,t,t,t,t,t,t,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Medium"});
fish.push({name:"Moray Eel",found:"Sea",bells:2000,annual:[f,f,f,f,f,f,f,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Narrow"});
fish.push({name:"Ribbon Eel",found:"Sea",bells:600,annual:[f,f,f,f,f,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Narrow"});
fish.push({name:"Tuna",found:"Pier",bells:7000,annual:[t,t,t,t,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Blue Marlin",found:"Pier",bells:10000,annual:[t,t,t,t,f,f,t,t,t,f,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Giant Trevally",found:"Pier",bells:4500,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Mahi-mahi",found:"Sea",bells:6000,annual:[f,f,f,f,t,t,t,t,t,t,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Ocean Sunfish",found:"Sea",bells:4000,annual:[f,f,f,f,f,f,t,t,t,f,f,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],size:"Giant Fin"});
fish.push({name:"Ray",found:"Sea",bells:3000,annual:[f,f,f,f,f,f,f,t,t,t,t,f],daily:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],size:"X Large"});
fish.push({name:"Saw Shark",found:"Sea",bells:12000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant Fin"});
fish.push({name:"Hammerhead Shark",found:"Sea",bells:8000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant Fin"});
fish.push({name:"Great White Shark",found:"Sea",bells:15000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Giant Fin"});
fish.push({name:"Whale Shark",found:"Sea",bells:13000,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant Fin"});
fish.push({name:"Suckerfish",found:"Sea",bells:1500,annual:[f,f,f,f,f,t,t,t,t,f,f,f],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Large Fin"});
fish.push({name:"Football Fish",found:"Sea",bells:2500,annual:[t,t,t,f,f,f,f,f,f,f,t,t],daily:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],size:"Large"});
fish.push({name:"Oarfish",found:"Sea",bells:9000,annual:[t,t,t,t,t,f,f,f,f,f,f,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});
fish.push({name:"Barreleye",found:"Sea",bells:15000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],size:"Small"});
fish.push({name:"Coelacanth",found:"Sea with rain",bells:15000,annual:[t,t,t,t,t,t,t,t,t,t,t,t],daily:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],size:"Giant"});