//0 name, 1 location (/ swimming pattern), 2 bells
//3 annual availability, 4 daily availability
//5 size (bug = 0, fish = 1 through 6)
//6 submission (0,1,2)

let fish = [];

fish.push(["Bitterling","River",900,[t,t,t,f,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Pale Chub","River",160,[t,t,t,t,t,t,t,t,t,t,t,t],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"X Small"]);
fish.push(["Crucian Carp","River",160,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Dace","River",240,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Carp","Pond",300,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Koi","Pond",4000,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Goldfish","Pond",1300,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Pop-eyed Goldfish","Pond",1300,[t,t,t,t,t,t,t,t,t,t,t,t],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"X Small"]);
fish.push(["Ranchu Goldfish","Pond",4500,[t,t,t,t,t,t,t,t,t,t,t,t],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"Small"]);
fish.push(["Killifish","Pond",300,[f,f,f,t,t,t,t,t,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Crawfish","Pond",200,[f,f,f,t,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Soft-shelled Turtle","River",3750,[f,f,f,f,f,f,f,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Snapping Turtle","River",5000,[f,f,f,t,t,t,t,t,t,t,f,f],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"X Large"]);
fish.push(["Tadpole","Pond",100,[f,f,t,t,t,t,t,f,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Frog","Pond",120,[f,f,f,f,t,t,t,t,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Freshwater Goby","River",400,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Loach","River",400,[f,f,t,t,t,f,f,f,f,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Catfish","Pond",800,[f,f,f,f,t,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Giant Snakehead","Pond",5500,[f,f,f,f,f,t,t,t,f,f,f,f],[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"X Large"]);
fish.push(["Bluegill","River",180,[t,t,t,t,t,t,t,t,t,t,t,t],[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"Small"]);
fish.push(["Yellow Perch","River",300,[t,t,t,f,f,f,f,f,f,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Black Bass","River",400,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Tilapia","River",800,[f,f,f,f,f,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Pike","River",1800,[f,f,f,f,f,f,f,f,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Large"]);
fish.push(["Pond Smelt","River",500,[t,t,f,f,f,f,f,f,f,f,f,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Sweetfish","River",900,[f,f,f,f,f,f,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Cherry Salmon","Clifftop river",1000,[f,f,t,t,t,t,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Char","Clifftop river",3800,[f,f,t,t,t,t,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Golden Trout","Clifftop river",15000,[f,f,t,t,t,t,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Stringfish","Clifftop river",15000,[t,t,t,f,f,f,f,f,f,f,f,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Salmon","Mouth of river",700,[f,f,f,f,f,f,f,f,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["King Salmon","Mouth of river",1800,[f,f,f,f,f,f,f,f,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Mitten Crab","River",2000,[f,f,f,f,f,f,f,f,t,t,t,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Guppy","River",1300,[f,f,f,t,t,t,t,t,t,f,f,f],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"X Small"]);
fish.push(["Nibble Fish","River",1500,[f,f,f,f,t,t,t,t,t,f,f,f],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"Small"]);
fish.push(["Angelfish","River",3000,[f,f,f,f,t,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Betta","River",2500,[f,f,f,f,t,t,t,t,t,t,f,f],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"Small"]);
fish.push(["Neon Tetra","River",500,[f,f,f,t,t,t,t,t,t,t,t,f],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"X Small"]);
fish.push(["Rainbowfish","River",800,[f,f,f,f,t,t,t,t,t,t,f,f],[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],"Small"]);
fish.push(["Piranha","River",2500,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],"Small"]);
fish.push(["Arowana","River",10000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Dorado","River",15000,[f,f,f,f,f,t,t,t,t,f,f,f],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],"X Large"]);
fish.push(["Gar","Pond",6000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Arapaima","River",10000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Saddled Bichir","River",4000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"Large"]);
fish.push(["Sturgeon","Mouth of river",10000,[t,t,t,f,f,f,f,f,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Sea Butterfly","Sea",1000,[t,t,t,f,f,f,f,f,f,f,f,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Sea Horse","Sea",1100,[f,f,f,t,t,t,t,t,t,t,t,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Clown Fish","Sea",650,[f,f,f,t,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Small"]);
fish.push(["Surgeonfish","Sea",1000,[f,f,f,t,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Butterfly Fish","Sea",1000,[f,f,f,t,t,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Napoleonfish","Sea",10000,[f,f,f,f,f,f,t,t,f,f,f,f],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],"Giant"]);
fish.push(["Zebra Turkeyfish","Sea",500,[f,f,f,t,t,t,t,t,t,t,t,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Blowfish","Sea",5000,[t,t,f,f,f,f,f,f,f,f,t,t],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t],"Medium"]);
fish.push(["Puffer Fish","Sea",250,[f,f,f,f,f,f,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Anchovy","Sea",200,[t,t,t,t,t,t,t,t,t,t,t,t],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],"Small"]);
fish.push(["Horse Mackerel","Sea",150,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Small"]);
fish.push(["Barred Knifejaw","Sea",5000,[f,f,t,t,t,t,t,t,t,t,t,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Sea Bass","Sea",400,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"X Large"]);
fish.push(["Red Snapper","Sea",3000,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Dab","Sea",300,[t,t,t,t,f,f,f,f,f,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Olive Flounder","Sea",800,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Squid","Sea",500,[t,t,t,t,t,t,t,t,f,f,f,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Medium"]);
fish.push(["Moray Eel","Sea",2000,[f,f,f,f,f,f,f,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Narrow"]);
fish.push(["Ribbon Eel","Sea",600,[f,f,f,f,f,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Narrow"]);
fish.push(["Tuna","Pier",7000,[t,t,t,t,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Blue Marlin","Pier",10000,[t,t,t,t,f,f,t,t,t,f,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Giant Trevally","Pier",4500,[f,f,f,f,t,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Mahi-mahi","Sea",6000,[f,f,f,f,t,t,t,t,t,t,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Ocean Sunfish","Sea",4000,[f,f,f,f,f,f,t,t,t,f,f,f],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],"Giant Fin"]);
fish.push(["Ray","Sea",3000,[f,f,f,f,f,f,f,t,t,t,t,f],[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],"X Large"]);
fish.push(["Saw Shark","Sea",12000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant Fin"]);
fish.push(["Hammerhead Shark","Sea",8000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant Fin"]);
fish.push(["Great White Shark","Sea",15000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Giant Fin"]);
fish.push(["Whale Shark","Sea",13000,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant Fin"]);
fish.push(["Suckerfish","Sea",1500,[f,f,f,f,f,t,t,t,t,f,f,f],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Large Fin"]);
fish.push(["Football Fish","Sea",2500,[t,t,t,f,f,f,f,f,f,f,t,t],[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],"Large"]);
fish.push(["Oarfish","Sea",9000,[t,t,t,t,t,f,f,f,f,f,f,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);
fish.push(["Barreleye","Sea",15000,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],"Small"]);
fish.push(["Coelacanth","Sea with rain",15000,[t,t,t,t,t,t,t,t,t,t,t,t],[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],"Giant"]);