let [t, f] = [true, false];
let catalogue = [];

catalogue.push({category:'Bug',number:1,name:'Common Butterfly',size:'null',context:'Flying',months:[t,t,t,t,t,t,f,f,t,t,t,t],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:160});
catalogue.push({category:'Bug',number:2,name:'Yellow Butterfly',size:'null',context:'Flying',months:[f,f,t,t,t,t,f,f,t,t,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:160});
catalogue.push({category:'Bug',number:3,name:'Tiger Butterfly',size:'null',context:'Flying',months:[f,f,t,t,t,t,t,t,t,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:240});
catalogue.push({category:'Bug',number:4,name:'Peacock Butterfly',size:'null',context:'Flying by hybrid flowers',months:[f,f,t,t,t,t,f,f,f,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:2500});
catalogue.push({category:'Bug',number:5,name:'Common Bluebottle',size:'null',context:'Flying',months:[f,f,f,t,t,t,t,t,f,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:300});
catalogue.push({category:'Bug',number:6,name:'Paper Kite Butterfly',size:'null',context:'Flying',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:1000});
catalogue.push({category:'Bug',number:7,name:'Great Purple Emperor',size:'null',context:'Flying',months:[f,f,f,f,t,t,t,t,f,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:3000});
catalogue.push({category:'Bug',number:8,name:'Monarch Butterfly',size:'null',context:'Flying',months:[f,f,f,f,f,f,f,f,t,t,t,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:140});
catalogue.push({category:'Bug',number:9,name:'Emperor Butterfly',size:'null',context:'Flying',months:[t,t,t,f,f,t,t,t,t,f,f,t],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:4000});
catalogue.push({category:'Bug',number:10,name:'Agrias Butterfly',size:'null',context:'Flying',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:3000});
catalogue.push({category:'Bug',number:11,name:'Rajah Brooke\'s Birdwing',size:'null',context:'Flying by purple flowers',months:[t,t,f,t,t,t,t,t,t,f,f,t],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:2500});
catalogue.push({category:'Bug',number:12,name:'Queen Alexandra\'s Birdwing',size:'null',context:'Flying',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:4000});
catalogue.push({category:'Bug',number:13,name:'Moth',size:'null',context:'Flying by light',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:130});
catalogue.push({category:'Bug',number:14,name:'Atlas Moth',size:'null',context:'On trees',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:3000});
catalogue.push({category:'Bug',number:15,name:'Madagascan Sunset Moth',size:'null',context:'Flying',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:2500});
catalogue.push({category:'Bug',number:16,name:'Long Locust',size:'null',context:'On ground',months:[f,f,f,t,t,t,t,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:200});
catalogue.push({category:'Bug',number:17,name:'Migratory Locust',size:'null',context:'On ground',months:[f,f,f,f,f,f,f,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:600});
catalogue.push({category:'Bug',number:18,name:'Rice Grasshopper',size:'null',context:'On ground',months:[f,f,f,f,f,f,f,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:160});
catalogue.push({category:'Bug',number:19,name:'Grasshopper',size:'null',context:'On ground',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:160});
catalogue.push({category:'Bug',number:20,name:'Cricket',size:'null',context:'Undeground at cricket noise',months:[f,f,f,f,f,f,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:130});
catalogue.push({category:'Bug',number:21,name:'Bell Cricket',size:'null',context:'On ground',months:[f,f,f,f,f,f,f,f,t,t,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:430});
catalogue.push({category:'Bug',number:22,name:'Mantis',size:'null',context:'On flowers',months:[f,f,t,t,t,t,t,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:430});
catalogue.push({category:'Bug',number:23,name:'Orchid Mantis',size:'null',context:'On white flowers',months:[f,f,t,t,t,t,t,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:2400});
catalogue.push({category:'Bug',number:24,name:'Honeybee',size:'null',context:'Flying',months:[f,f,t,t,t,t,t,f,f,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:200});
catalogue.push({category:'Bug',number:25,name:'Wasp',size:'null',context:'Falls from shaking trees',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2500});
catalogue.push({category:'Bug',number:26,name:'Brown Cicada',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:250});
catalogue.push({category:'Bug',number:27,name:'Robust Cicada',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:300});
catalogue.push({category:'Bug',number:28,name:'Giant Cicada',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:600});
catalogue.push({category:'Bug',number:29,name:'Walker Cicada',size:'null',context:'On trees',months:[f,f,f,f,f,f,f,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:400});
catalogue.push({category:'Bug',number:30,name:'Evening Cicada',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,f,f,f,f,f],value:660});
catalogue.push({category:'Bug',number:31,name:'Cicada Shell',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:10});
catalogue.push({category:'Bug',number:32,name:'Red Dragonfly',size:'null',context:'Flying',months:[f,f,f,f,f,f,f,f,t,t,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:180});
catalogue.push({category:'Bug',number:33,name:'Darner Dragonfly',size:'null',context:'Flying',months:[f,f,f,t,t,t,t,t,t,t,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:230});
catalogue.push({category:'Bug',number:34,name:'Banded Dragonfly',size:'null',context:'Flying',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:4500});
catalogue.push({category:'Bug',number:35,name:'Damselfly',size:'null',context:'Flying',months:[t,t,f,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Bug',number:36,name:'Firefly',size:'null',context:'Flying',months:[f,f,f,f,f,t,f,f,f,f,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:300});
catalogue.push({category:'Bug',number:37,name:'Mole Cricket',size:'null',context:'Underground',months:[t,t,t,t,t,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Bug',number:38,name:'Pondskater',size:'null',context:'Ponds',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:130});
catalogue.push({category:'Bug',number:39,name:'Diving Beetle',size:'null',context:'Ponds and rivers',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f],value:800});
catalogue.push({category:'Bug',number:40,name:'Giant Water Bug',size:'null',context:'Ponds and rivers',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:2000});
catalogue.push({category:'Bug',number:41,name:'Stinkbug',size:'null',context:'On flowers',months:[f,f,t,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:120});
catalogue.push({category:'Bug',number:42,name:'Man-faced Stink Bug',size:'null',context:'On flowers',months:[f,f,t,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:1000});
catalogue.push({category:'Bug',number:43,name:'Ladybug',size:'null',context:'On flowers',months:[f,f,t,t,f,f,f,f,f,t,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f],value:200});
catalogue.push({category:'Bug',number:44,name:'Tiger Beetle',size:'null',context:'On ground',months:[f,t,t,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1500});
catalogue.push({category:'Bug',number:45,name:'Jewel Beetle',size:'null',context:'On tree stumps',months:[f,f,f,t,t,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2400});
catalogue.push({category:'Bug',number:46,name:'Violin Beetle',size:'null',context:'On tree stumps',months:[f,f,f,f,t,t,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:450});
catalogue.push({category:'Bug',number:47,name:'Citrus Long-horned Beetle',size:'null',context:'On tree stumps',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:350});
catalogue.push({category:'Bug',number:48,name:'Rosalia Batesi Beetle',size:'null',context:'On tree stumps',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:3000});
catalogue.push({category:'Bug',number:49,name:'Blue Weevil Beetle',size:'null',context:'On palm trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:800});
catalogue.push({category:'Bug',number:50,name:'Dung Beetle',size:'null',context:'Pushing snowballs',months:[t,t,f,f,f,f,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:3000});
catalogue.push({category:'Bug',number:51,name:'Earth-boring Dung Beetle',size:'null',context:'On ground',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t],value:300});
catalogue.push({category:'Bug',number:52,name:'Scarab Beetle',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Bug',number:53,name:'Drone Beetle',size:'null',context:'On trees',months:[f,f,f,f,f,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:200});
catalogue.push({category:'Bug',number:54,name:'Goliath Beetle',size:'null',context:'On coconut trees',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Bug',number:55,name:'Saw Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2000});
catalogue.push({category:'Bug',number:56,name:'Miyama Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t],value:1000});
catalogue.push({category:'Bug',number:57,name:'Giant Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:10000});
catalogue.push({category:'Bug',number:58,name:'Rainbow Stag',size:'null',context:'On trees',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:6000});
catalogue.push({category:'Bug',number:59,name:'Cyclommatus Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Bug',number:60,name:'Golden Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:12000});
catalogue.push({category:'Bug',number:61,name:'Giraffe Stag',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:12000});
catalogue.push({category:'Bug',number:62,name:'Horned Dynastid',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:1350});
catalogue.push({category:'Bug',number:63,name:'Horned Atlas',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Bug',number:64,name:'Horned Elephant',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Bug',number:65,name:'Horned Hercules',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f],value:12000});
catalogue.push({category:'Bug',number:66,name:'Walking Stick',size:'null',context:'On trees',months:[f,f,f,f,f,f,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Bug',number:67,name:'Walking Leaf',size:'null',context:'Near trees, looks like leaf',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Bug',number:68,name:'Bagworm',size:'null',context:'Falls from shaking trees',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Bug',number:69,name:'Ant',size:'null',context:'On rotten food',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:80});
catalogue.push({category:'Bug',number:70,name:'Hermit Crab',size:'null',context:'Beach',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Bug',number:71,name:'Wharf Roach',size:'null',context:'On rocks at beach',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:200});
catalogue.push({category:'Bug',number:72,name:'Fly',size:'null',context:'On trash items',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:60});
catalogue.push({category:'Bug',number:73,name:'Mosquito',size:'null',context:'Flying',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:130});
catalogue.push({category:'Bug',number:74,name:'Flea',size:'null',context:'On villagers',months:[f,f,f,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:70});
catalogue.push({category:'Bug',number:75,name:'Snail',size:'null',context:'On rocks with rain',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t],value:250});
catalogue.push({category:'Bug',number:76,name:'Pill Bug',size:'null',context:'Hit rocks',months:[t,t,t,t,t,t,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t],value:250});
catalogue.push({category:'Bug',number:77,name:'Centipede',size:'null',context:'Hit rocks',months:[t,t,t,t,t,t,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:300});
catalogue.push({category:'Bug',number:78,name:'Spider',size:'null',context:'Falls from shaking trees',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:480});
catalogue.push({category:'Bug',number:79,name:'Tarantula',size:'null',context:'On ground',months:[t,t,t,t,f,f,f,f,f,f,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:8000});
catalogue.push({category:'Bug',number:80,name:'Scorpion',size:'null',context:'On ground',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t],value:8000});
catalogue.push({category:'Fish',number:1,name:'Bitterling',size:'X Small',context:'River',months:[t,t,t,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:900});
catalogue.push({category:'Fish',number:2,name:'Pale Chub',size:'X Small',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:160});
catalogue.push({category:'Fish',number:3,name:'Crucian Carp',size:'Small',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:160});
catalogue.push({category:'Fish',number:4,name:'Dace',size:'Medium',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:240});
catalogue.push({category:'Fish',number:5,name:'Carp',size:'Large',context:'Pond',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:300});
catalogue.push({category:'Fish',number:6,name:'Koi',size:'Large',context:'Pond',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:4000});
catalogue.push({category:'Fish',number:7,name:'Goldfish',size:'X Small',context:'Pond',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1300});
catalogue.push({category:'Fish',number:8,name:'Pop-eyed Goldfish',size:'X Small',context:'Pond',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:1300});
catalogue.push({category:'Fish',number:9,name:'Ranchu Goldfish',size:'Small',context:'Pond',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:4500});
catalogue.push({category:'Fish',number:10,name:'Killifish',size:'X Small',context:'Pond',months:[f,f,f,t,t,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:300});
catalogue.push({category:'Fish',number:11,name:'Crawfish',size:'Small',context:'Pond',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:200});
catalogue.push({category:'Fish',number:12,name:'Soft-shelled Turtle',size:'Large',context:'River',months:[f,f,f,f,f,f,f,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:3750});
catalogue.push({category:'Fish',number:13,name:'Snapping Turtle',size:'X Large',context:'River',months:[f,f,f,t,t,t,t,t,t,t,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:5000});
catalogue.push({category:'Fish',number:14,name:'Tadpole',size:'X Small',context:'Pond',months:[f,f,t,t,t,t,t,f,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:100});
catalogue.push({category:'Fish',number:15,name:'Frog',size:'Small',context:'Pond',months:[f,f,f,f,t,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:120});
catalogue.push({category:'Fish',number:16,name:'Freshwater Goby',size:'Small',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:400});
catalogue.push({category:'Fish',number:17,name:'Loach',size:'Small',context:'River',months:[f,f,t,t,t,f,f,f,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:400});
catalogue.push({category:'Fish',number:18,name:'Catfish',size:'Large',context:'Pond',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:800});
catalogue.push({category:'Fish',number:19,name:'Giant Snakehead',size:'X Large',context:'Pond',months:[f,f,f,f,f,t,t,t,f,f,f,f],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:5500});
catalogue.push({category:'Fish',number:20,name:'Bluegill',size:'Small',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:180});
catalogue.push({category:'Fish',number:21,name:'Yellow Perch',size:'Medium',context:'River',months:[t,t,t,f,f,f,f,f,f,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:300});
catalogue.push({category:'Fish',number:22,name:'Black Bass',size:'Large',context:'River',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:400});
catalogue.push({category:'Fish',number:23,name:'Tilapia',size:'Medium',context:'River',months:[f,f,f,f,f,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:800});
catalogue.push({category:'Fish',number:24,name:'Pike',size:'X Large',context:'River',months:[f,f,f,f,f,f,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1800});
catalogue.push({category:'Fish',number:25,name:'Pond Smelt',size:'Small',context:'River',months:[t,t,f,f,f,f,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Fish',number:26,name:'Sweetfish',size:'Medium',context:'River',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:900});
catalogue.push({category:'Fish',number:27,name:'Cherry Salmon',size:'Medium',context:'Clifftop river',months:[f,f,t,t,t,t,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Fish',number:28,name:'Char',size:'Medium',context:'Clifftop river',months:[f,f,t,t,t,t,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:3800});
catalogue.push({category:'Fish',number:29,name:'Golden Trout',size:'Medium',context:'Clifftop river',months:[f,f,t,t,t,t,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:15000});
catalogue.push({category:'Fish',number:30,name:'Stringfish',size:'Giant',context:'Clifftop river',months:[t,t,t,f,f,f,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:15000});
catalogue.push({category:'Fish',number:31,name:'Salmon',size:'Large',context:'Mouth of river',months:[f,f,f,f,f,f,f,f,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:700});
catalogue.push({category:'Fish',number:32,name:'King Salmon',size:'Giant',context:'Mouth of river',months:[f,f,f,f,f,f,f,f,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1800});
catalogue.push({category:'Fish',number:33,name:'Mitten Crab',size:'Small',context:'River',months:[f,f,f,f,f,f,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:2000});
catalogue.push({category:'Fish',number:34,name:'Guppy',size:'X Small',context:'River',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:1300});
catalogue.push({category:'Fish',number:35,name:'Nibble Fish',size:'Small',context:'River',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:1500});
catalogue.push({category:'Fish',number:36,name:'Angelfish',size:'Small',context:'River',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:3000});
catalogue.push({category:'Fish',number:37,name:'Betta',size:'Small',context:'River',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:2500});
catalogue.push({category:'Fish',number:38,name:'Neon Tetra',size:'X Small',context:'River',months:[f,f,f,t,t,t,t,t,t,t,t,f],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:500});
catalogue.push({category:'Fish',number:39,name:'Rainbowfish',size:'Small',context:'River',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[f,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f],value:800});
catalogue.push({category:'Fish',number:40,name:'Piranha',size:'Small',context:'River',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],value:2500});
catalogue.push({category:'Fish',number:41,name:'Arowana',size:'Large',context:'River',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Fish',number:42,name:'Dorado',size:'X Large',context:'River',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:15000});
catalogue.push({category:'Fish',number:43,name:'Gar',size:'Giant',context:'Pond',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:6000});
catalogue.push({category:'Fish',number:44,name:'Arapaima',size:'Giant',context:'River',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Fish',number:45,name:'Saddled Bichir',size:'Large',context:'River',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:4000});
catalogue.push({category:'Fish',number:46,name:'Sturgeon',size:'Giant',context:'Mouth of river',months:[t,t,t,f,f,f,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Fish',number:47,name:'Sea Butterfly',size:'X Small',context:'Sea',months:[t,t,t,f,f,f,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Fish',number:48,name:'Seahorse',size:'X Small',context:'Sea',months:[f,f,f,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1100});
catalogue.push({category:'Fish',number:49,name:'Clownfish',size:'X Small',context:'Sea',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:650});
catalogue.push({category:'Fish',number:50,name:'Surgeonfish',size:'Small',context:'Sea',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Fish',number:51,name:'Butterfly Fish',size:'Small',context:'Sea',months:[f,f,f,t,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Fish',number:52,name:'Napoleonfish',size:'Giant',context:'Sea',months:[f,f,f,f,f,f,t,t,f,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:10000});
catalogue.push({category:'Fish',number:53,name:'Zebra Turkeyfish',size:'Medium',context:'Sea',months:[f,f,f,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Fish',number:54,name:'Blowfish',size:'Medium',context:'Sea',months:[t,t,f,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t,t,t,t],value:5000});
catalogue.push({category:'Fish',number:55,name:'Puffer Fish',size:'Medium',context:'Sea',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:250});
catalogue.push({category:'Fish',number:56,name:'Anchovy',size:'Small',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:200});
catalogue.push({category:'Fish',number:57,name:'Horse Mackerel',size:'Small',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:150});
catalogue.push({category:'Fish',number:58,name:'Barred Knifejaw',size:'Medium',context:'Sea',months:[f,f,t,t,t,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:5000});
catalogue.push({category:'Fish',number:59,name:'Sea Bass',size:'X Large',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:400});
catalogue.push({category:'Fish',number:60,name:'Red Snapper',size:'Large',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:3000});
catalogue.push({category:'Fish',number:61,name:'Dab',size:'Medium',context:'Sea',months:[t,t,t,t,f,f,f,f,f,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:300});
catalogue.push({category:'Fish',number:62,name:'Olive Flounder',size:'Large',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:800});
catalogue.push({category:'Fish',number:63,name:'Squid',size:'Medium',context:'Sea',months:[t,t,t,t,t,t,t,t,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Fish',number:64,name:'Moray Eel',size:'Narrow',context:'Sea',months:[f,f,f,f,f,f,f,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2000});
catalogue.push({category:'Fish',number:65,name:'Ribbon Eel',size:'Narrow',context:'Sea',months:[f,f,f,f,f,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Fish',number:66,name:'Tuna',size:'Giant',context:'Pier',months:[t,t,t,t,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:7000});
catalogue.push({category:'Fish',number:67,name:'Blue Marlin',size:'Giant',context:'Pier',months:[t,t,t,t,f,f,t,t,t,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Fish',number:68,name:'Giant Trevally',size:'Large',context:'Pier',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:4500});
catalogue.push({category:'Fish',number:69,name:'Mahi-mahi',size:'Large',context:'Sea',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:6000});
catalogue.push({category:'Fish',number:70,name:'Ocean Sunfish',size:'Giant Fin',context:'Sea',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:4000});
catalogue.push({category:'Fish',number:71,name:'Ray',size:'X Large',context:'Sea',months:[f,f,f,f,f,f,f,t,t,t,t,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:3000});
catalogue.push({category:'Fish',number:72,name:'Saw Shark',size:'Giant Fin',context:'Sea',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:12000});
catalogue.push({category:'Fish',number:73,name:'Hammerhead Shark',size:'Giant Fin',context:'Sea',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Fish',number:74,name:'Great White Shark',size:'Giant Fin',context:'Sea',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:15000});
catalogue.push({category:'Fish',number:75,name:'Whale Shark',size:'Giant Fin',context:'Sea',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:13000});
catalogue.push({category:'Fish',number:76,name:'Suckerfish',size:'Large Fin',context:'Sea',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1500});
catalogue.push({category:'Fish',number:77,name:'Football Fish',size:'Large',context:'Sea',months:[t,t,t,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:2500});
catalogue.push({category:'Fish',number:78,name:'Oarfish',size:'Giant',context:'Sea',months:[t,t,t,t,t,f,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:9000});
catalogue.push({category:'Fish',number:79,name:'Barreleye',size:'Small',context:'Sea',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:15000});
catalogue.push({category:'Fish',number:80,name:'Coelacanth',size:'Giant',context:'Sea with rain',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:15000});
catalogue.push({category:'Deep Sea',number:1,name:'Seaweed',size:'Large',context:'Stationary',months:[t,t,t,t,t,t,t,f,f,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Deep Sea',number:2,name:'Sea grapes',size:'Small',context:'Stationary',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:900});
catalogue.push({category:'Deep Sea',number:3,name:'Sea cucumber',size:'Medium',context:'Slow consistent movement',months:[t,t,t,t,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Deep Sea',number:4,name:'Sea pig',size:'Small',context:'Quick long lunges',months:[t,t,f,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Deep Sea',number:5,name:'Sea star',size:'Small',context:'Slow short lunges',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Deep Sea',number:6,name:'Sea urchin',size:'Small',context:'Slow consistent movement',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1700});
catalogue.push({category:'Deep Sea',number:7,name:'Slate pencil urchin',size:'Medium',context:'Moderate consistent movement',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:2000});
catalogue.push({category:'Deep Sea',number:8,name:'Sea anemone',size:'Large',context:'Stationary',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:500});
catalogue.push({category:'Deep Sea',number:9,name:'Moon jellyfish',size:'Small',context:'Slow consistent movement',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Deep Sea',number:10,name:'Sea slug',size:'X Small',context:'Slow consistent movement',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Deep Sea',number:11,name:'Pearl oyster',size:'Small',context:'Moderate long lunges',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2800});
catalogue.push({category:'Deep Sea',number:12,name:'Mussel',size:'Small',context:'Slow consistent movement',months:[f,f,f,f,f,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1500});
catalogue.push({category:'Deep Sea',number:13,name:'Oyster',size:'Small',context:'Moderate short lunges',months:[t,t,f,f,f,f,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1100});
catalogue.push({category:'Deep Sea',number:14,name:'Scallop',size:'Medium',context:'Slow long lunges',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1200});
catalogue.push({category:'Deep Sea',number:15,name:'Whelk',size:'Small',context:'Slow consistent movement',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Deep Sea',number:16,name:'Turban shell',size:'Small',context:'Slow',months:[f,f,t,t,t,f,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1000});
catalogue.push({category:'Deep Sea',number:17,name:'Abalone',size:'Medium',context:'Moderate consistent movement',months:[t,f,f,f,f,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:2000});
catalogue.push({category:'Deep Sea',number:18,name:'Gigas giant clam',size:'X Large',context:'Quick long lunges',months:[f,f,f,f,t,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:15000});
catalogue.push({category:'Deep Sea',number:19,name:'Chambered nautilus',size:'Medium',context:'Slow',months:[f,f,t,t,t,t,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:1800});
catalogue.push({category:'Deep Sea',number:20,name:'Octopus',size:'Medium',context:'Moderate long lunges',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1200});
catalogue.push({category:'Deep Sea',number:21,name:'Umbrella octopus',size:'Small',context:'Quick long lunges',months:[f,f,t,t,t,f,f,f,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:6000});
catalogue.push({category:'Deep Sea',number:22,name:'Vampire squid',size:'Medium',context:'Quick long lunges',months:[f,f,f,f,t,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,f,t,t,t,t,t,t,t],value:10000});
catalogue.push({category:'Deep Sea',number:23,name:'Firefly squid',size:'X Small',context:'Slow',months:[f,f,t,t,t,t,f,f,f,f,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:1400});
catalogue.push({category:'Deep Sea',number:24,name:'Gazami crab',size:'Medium',context:'Moderate long lunges',months:[f,f,f,f,f,t,t,t,t,t,t,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:2200});
catalogue.push({category:'Deep Sea',number:25,name:'Dungeness crab',size:'Medium',context:'Moderate consistent movement',months:[t,t,t,t,t,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1900});
catalogue.push({category:'Deep Sea',number:26,name:'Snow crab',size:'Large',context:'Quick short lunges',months:[t,t,t,t,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:6000});
catalogue.push({category:'Deep Sea',number:27,name:'Red king crab',size:'Large',context:'Quick',months:[t,t,t,f,f,f,f,f,f,f,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:8000});
catalogue.push({category:'Deep Sea',number:28,name:'Acorn barnacle',size:'X Small',context:'Stationary',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:600});
catalogue.push({category:'Deep Sea',number:29,name:'Spider crab',size:'X Large',context:'Quick',months:[f,f,t,t,f,f,f,f,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:12000});
catalogue.push({category:'Deep Sea',number:30,name:'Tiger prawn',size:'Small',context:'Moderate consistent movement',months:[f,f,f,f,f,t,t,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:3000});
catalogue.push({category:'Deep Sea',number:31,name:'Sweet shrimp',size:'Small',context:'Slow',months:[t,t,f,f,f,f,f,f,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:1400});
catalogue.push({category:'Deep Sea',number:32,name:'Mantis shrimp',size:'Small',context:'Quick short lunges',months:[t,t,t,t,t,t,t,t,t,t,t,t],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:2500});
catalogue.push({category:'Deep Sea',number:33,name:'Spiny Lobster',size:'Large',context:'Fast',months:[f,f,f,f,f,f,f,f,f,t,t,t],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:5000});
catalogue.push({category:'Deep Sea',number:34,name:'Lobster',size:'Large',context:'Quick',months:[t,f,f,t,t,t,f,f,f,f,f,t],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:4500});
catalogue.push({category:'Deep Sea',number:35,name:'Giant isopod',size:'Medium',context:'Quick long lunges',months:[f,f,f,f,f,f,t,t,t,t,f,f],hours:[t,t,t,t,f,f,f,f,f,t,t,t,t,t,t,t,f,f,f,f,f,t,t,t],value:12000});
catalogue.push({category:'Deep Sea',number:36,name:'Horseshoe crab',size:'Medium',context:'Quick short lunges',months:[f,f,f,f,f,f,t,t,t,f,f,f],hours:[t,t,t,t,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,t,t,t],value:2500});
catalogue.push({category:'Deep Sea',number:37,name:'Sea pineapple',size:'Small',context:'Slow long lunges',months:[f,f,f,t,t,t,t,t,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:1500});
catalogue.push({category:'Deep Sea',number:38,name:'Spotted garden eel',size:'Small',context:'Slow consistent movement',months:[f,f,f,f,t,t,t,t,t,t,f,f],hours:[f,f,f,f,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,f,f,f],value:1100});
catalogue.push({category:'Deep Sea',number:39,name:'Flatworm',size:'X Small',context:'Slow short movement',months:[f,f,f,f,f,f,f,t,t,f,f,f],hours:[t,t,t,t,t,t,t,t,t,f,f,f,f,f,f,f,t,t,t,t,t,t,t,t],value:700});
catalogue.push({category:'Deep Sea',number:40,name:'Venus\' flower basket',size:'Medium',context:'Quick long lunges',months:[t,t,f,f,f,f,f,f,f,f,f,f],hours:[t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t],value:5000});

catalogue.push({category:'Fossil',name:'Ankylo skull',family:'Ankylosaurus',value:3500});
catalogue.push({category:'Fossil',name:'Ankylo tail',family:'Ankylosaurus',value:2500});
catalogue.push({category:'Fossil',name:'Ankylo torso',family:'Ankylosaurus',value:3000});
catalogue.push({category:'Fossil',name:'Archelon skull',family:'Archelon',value:4000});
catalogue.push({category:'Fossil',name:'Archelon tail',family:'Archelon',value:3500});
catalogue.push({category:'Fossil',name:'Brachio chest',family:'Brachiosaurus',value:5500});
catalogue.push({category:'Fossil',name:'Brachio pelvis',family:'Brachiosaurus',value:5000});
catalogue.push({category:'Fossil',name:'Brachio skull',family:'Brachiosaurus',value:6000});
catalogue.push({category:'Fossil',name:'Brachio tail',family:'Brachiosaurus',value:5500});
catalogue.push({category:'Fossil',name:'Deinony tail',family:'Deinonychus',value:2500});
catalogue.push({category:'Fossil',name:'Deinony torso',family:'Deinonychus',value:3000});
catalogue.push({category:'Fossil',name:'Dimetrodon skull',family:'Dimetrodon',value:5500});
catalogue.push({category:'Fossil',name:'Dimetrodon torso',family:'Dimetrodon',value:5000});
catalogue.push({category:'Fossil',name:'Diplo chest',family:'Diplodocus',value:4000});
catalogue.push({category:'Fossil',name:'Diplo neck',family:'Diplodocus',value:4500});
catalogue.push({category:'Fossil',name:'Diplo pelvis',family:'Diplodocus',value:4500});
catalogue.push({category:'Fossil',name:'Diplo skull',family:'Diplodocus',value:5000});
catalogue.push({category:'Fossil',name:'Diplo tail',family:'Diplodocus',value:5000});
catalogue.push({category:'Fossil',name:'Diplo tail tip',family:'Diplodocus',value:4000});
catalogue.push({category:'Fossil',name:'Iguanodon skull',family:'Iguanodon',value:4000});
catalogue.push({category:'Fossil',name:'Iguanodon tail',family:'Iguanodon',value:3000});
catalogue.push({category:'Fossil',name:'Iguanodon torso',family:'Iguanodon',value:3500});
catalogue.push({category:'Fossil',name:'Mammoth skull',family:'Mammoth',value:3000});
catalogue.push({category:'Fossil',name:'Mammoth torso',family:'Mammoth',value:2500});
catalogue.push({category:'Fossil',name:'Megacero skull',family:'Megacerops',value:4500});
catalogue.push({category:'Fossil',name:'Megacero tail',family:'Megacerops',value:3000});
catalogue.push({category:'Fossil',name:'Megacero torso',family:'Megacerops',value:3500});
catalogue.push({category:'Fossil',name:'Left megalo side',family:'Megaloceros',value:4000});
catalogue.push({category:'Fossil',name:'Right megalo side',family:'Megaloceros',value:5500});
catalogue.push({category:'Fossil',name:'Ophthalmo skull',family:'Ophthalmosaurus',value:2500});
catalogue.push({category:'Fossil',name:'Ophthalmo torso',family:'Ophthalmosaurus',value:2000});
catalogue.push({category:'Fossil',name:'Pachy skull',family:'Pachycephalosaurus',value:4000});
catalogue.push({category:'Fossil',name:'Pachy tail',family:'Pachycephalosaurus',value:3500});
catalogue.push({category:'Fossil',name:'Parasaur skull',family:'Parasaurolophus',value:3500});
catalogue.push({category:'Fossil',name:'Parasaur tail',family:'Parasaurolophus',value:2500});
catalogue.push({category:'Fossil',name:'Parasaur torso',family:'Parasaurolophus',value:3000});
catalogue.push({category:'Fossil',name:'Plesio skull',family:'Plesiosaurus',value:4000});
catalogue.push({category:'Fossil',name:'Plesio tail',family:'Plesiosaurus',value:4500});
catalogue.push({category:'Fossil',name:'Plesio torso',family:'Plesiosaurus',value:4500});
catalogue.push({category:'Fossil',name:'Left ptera wing',family:'Pteranodon',value:4500});
catalogue.push({category:'Fossil',name:'Ptera body',family:'Pteranodon',value:4000});
catalogue.push({category:'Fossil',name:'Right ptera wing',family:'Pteranodon',value:4500});
catalogue.push({category:'Fossil',name:'Left quetzal wing',family:'Quetzalcoatlus',value:5000});
catalogue.push({category:'Fossil',name:'Quetzal torso',family:'Quetzalcoatlus',value:4500});
catalogue.push({category:'Fossil',name:'Right quetzal wing',family:'Quetzalcoatlus',value:5000});
catalogue.push({category:'Fossil',name:'Sabertooth skull',family:'Sabertooth Tiger',value:2500});
catalogue.push({category:'Fossil',name:'Sabertooth tail',family:'Sabertooth Tiger',value:2000});
catalogue.push({category:'Fossil',name:'Spino skull',family:'Spinosaurus',value:4000});
catalogue.push({category:'Fossil',name:'Spino tail',family:'Spinosaurus',value:2500});
catalogue.push({category:'Fossil',name:'Spino torso',family:'Spinosaurus',value:3000});
catalogue.push({category:'Fossil',name:'Stego skull',family:'Stegosaurus',value:5000});
catalogue.push({category:'Fossil',name:'Stego tail',family:'Stegosaurus',value:4000});
catalogue.push({category:'Fossil',name:'Stego torso',family:'Stegosaurus',value:4500});
catalogue.push({category:'Fossil',name:'T. rex skull',family:'T. Rex',value:6000});
catalogue.push({category:'Fossil',name:'T. rex tail',family:'T. Rex',value:5000});
catalogue.push({category:'Fossil',name:'T. rex torso',family:'T. Rex',value:5500});
catalogue.push({category:'Fossil',name:'Tricera skull',family:'Triceratops',value:5500});
catalogue.push({category:'Fossil',name:'Tricera tail',family:'Triceratops',value:4500});
catalogue.push({category:'Fossil',name:'Tricera torso',family:'Triceratops',value:5000});
catalogue.push({category:'Fossil',name:'Acanthostega',family:'',value:2000});
catalogue.push({category:'Fossil',name:'Amber',family:'',value:1200});
catalogue.push({category:'Fossil',name:'Ammonite',family:'',value:1100});
catalogue.push({category:'Fossil',name:'Anomalocaris',family:'',value:2000});
catalogue.push({category:'Fossil',name:'Archaeopteryx',family:'',value:1300});
catalogue.push({category:'Fossil',name:'Australopith',family:'',value:1100});
catalogue.push({category:'Fossil',name:'Coprolite',family:'',value:1100});
catalogue.push({category:'Fossil',name:'Dinosaur track',family:'',value:1000});
catalogue.push({category:'Fossil',name:'Dunkleosteus',family:'',value:3500});
catalogue.push({category:'Fossil',name:'Eusthenopteron',family:'',value:2000});
catalogue.push({category:'Fossil',name:'Juramaia',family:'',value:1500});
catalogue.push({category:'Fossil',name:'Myllokunmingia',family:'',value:1500});
catalogue.push({category:'Fossil',name:'Shark-tooth pattern',family:'',value:1000});
catalogue.push({category:'Fossil',name:'Trilobite',family:'',value:1300});

catalogue.push({category:'Art',name:'Academic Painting', fake: 'fake if stained with coffee', value: 1245, art: 'Vitruvian Man'});
catalogue.push({category:'Art',name:'Amazing Painting', fake: 'fake if man in red not wearing hat', value: 1245, art: 'The Night Watch'});
catalogue.push({category:'Art',name:'Basic Painting', fake: 'fake if has bangs', value: 1245, art: 'The Blue Boy'});
catalogue.push({category:'Art',name:'Calm Painting', fake: 'always real', value: 1245, art: 'A Sunday Afternoon on the Island ...'});
catalogue.push({category:'Art',name:'Common Painting', fake: 'always real', value: 1245, art: 'The Gleaners'});
catalogue.push({category:'Art',name:'Detailed Painting', fake: 'fake if has purple flowers', value: 1245, art: 'Ajisai Sōkeizu'});
catalogue.push({category:'Art',name:'Dynamic Painting', fake: 'always real', value: 1245, art: 'Thirty-Six Views of Mount Fuji The ...'});
catalogue.push({category:'Art',name:'Famous Painting', fake: 'fake if has eyebrows', value: 1245, art: 'Mona Lisa'});
catalogue.push({category:'Art',name:'Flowery Painting', fake: 'always real', value: 1245, art: 'Sunflowers'});
catalogue.push({category:'Art',name:'Glowing Painting', fake: 'always real', value: 1245, art: 'The Fighting Temeraire'});
catalogue.push({category:'Art',name:'Graceful Painting', fake: 'fake if little empty space at top', value: 1245, art: 'Beauty Looking Back'});
catalogue.push({category:'Art',name:'Jolly Painting', fake: 'fake if lacks artichoke in chest', value: 1245, art: 'Summer'});
catalogue.push({category:'Art',name:'Moody Painting', fake: 'always real', value: 1245, art: 'The Sower'});
catalogue.push({category:'Art',name:'Moving Painting', fake: 'fake if no tree in top right', value: 1245, art: 'The Birth of Venus'});
catalogue.push({category:'Art',name:'Mysterious Painting', fake: 'always real', value: 1245, art: 'Isle of The Dead'});
catalogue.push({category:'Art',name:'Nice Painting', fake: 'always real', value: 1245, art: 'The Fifer'});
catalogue.push({category:'Art',name:'Perfect Painting', fake: 'always real', value: 1245, art: 'Apples and Oranges'});
catalogue.push({category:'Art',name:'Proper Painting', fake: 'always real', value: 1245, art: 'A Bar at The Folies-Bergère'});
catalogue.push({category:'Art',name:'Quaint Painting', fake: 'fake if milk is more than a trickle', value: 1245, art: 'The Milkmaid'});
catalogue.push({category:'Art',name:'Scary Painting', fake: 'fake if eyebrows aren\'t angry', value: 1245, art: 'Ōtani Oniji the 3rd as Yakko Edobei'});
catalogue.push({category:'Art',name:'Scenic Painting', fake: 'fake if only one person on hill', value: 1245, art: 'The Hunters in The Snow'});
catalogue.push({category:'Art',name:'Serene Painting', fake: 'fake if animal is gray', value: 1245, art: 'Lady with an Ermine'});
catalogue.push({category:'Art',name:'Sinking Painting', fake: 'always real', value: 1245, art: 'Ophelia'});
catalogue.push({category:'Art',name:'Solemn Painting', fake: 'fake if man in back giving thumbs up', value: 1245, art: 'Las Meninas'});
catalogue.push({category:'Art',name:'Twinkling Painting', fake: 'always real', value: 1245, art: 'The Starry Night'});
catalogue.push({category:'Art',name:'Warm Painting', fake: 'always real', value: 1245, art: 'The Clothed Maja'});
catalogue.push({category:'Art',name:'Wild Painting Left Half', fake: 'fake if dark skin', value: 1245, art: 'Folding Screen of Fūjin and Raijin'});
catalogue.push({category:'Art',name:'Wild Painting Right Half', fake: 'fake if light skin', value: 1245, art: 'Folding Screen of Fūjin and Raijin'});
catalogue.push({category:'Art',name:'Wistful Painting', fake: 'fake if earring is star', value: 1245, art: 'Girl with a Pearl Earring'});
catalogue.push({category:'Art',name:'Worthy Painting', fake: 'always real', value: 1245, art: 'Liberty Leading the People'});
catalogue.push({category:'Art',name:'Ancient Statue', fake: 'fake if has antennae', value: 1245, art: 'Shakōki dogū'});
catalogue.push({category:'Art',name:'Beautiful Statue', fake: 'fake if wearing necklace', value: 1245, art: 'Venus de Milo'});
catalogue.push({category:'Art',name:'Familiar Statue', fake: 'always real', value: 1245, art: 'The Thinker'});
catalogue.push({category:'Art',name:'Gallant Statue', fake: 'fake if holding book', value: 1245, art: 'David'});
catalogue.push({category:'Art',name:'Great Statue', fake: 'always real', value: 1245, art: 'Kamehameha Statue Kohala'});
catalogue.push({category:'Art',name:'Informative Status', fake: 'fake if blue', value: 1245, art: 'Rosetta Stone'});
catalogue.push({category:'Art',name:'Motherly Statue', fake: 'fake if sticking out tongue', value: 1245, art: 'Capitoline Wolf'});
catalogue.push({category:'Art',name:'Mystic Statue', fake: 'fake if has earring', value: 1245, art: 'Bust of Nefertiti'});
catalogue.push({category:'Art',name:'Robust Statue', fake: 'fake if wearing watch', value: 1245, art: 'Townley Discobolus'});
catalogue.push({category:'Art',name:'Rock-head Statue', fake: 'fake if smiling', value: 1245, art: 'Olmec colossal head 1'});
catalogue.push({category:'Art',name:'Tremendous Statue', fake: 'fake if has three handles intead of two', value: 1245, art: 'Houmuwu ding'});
catalogue.push({category:'Art',name:'Valiant Statue', fake: 'fake if its left foot in front', value: 1245, art: 'Winged Victory of Samothrace'});
catalogue.push({category:'Art',name:'Warrior Statue', fake: 'fake if holding shovel', value: 1245, art: 'Terracotta Army soldier'});